export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const INIT_INGREDIENTS_FAILED = "INIT_INGREDIENTS_FAILED";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";