// BurgerBuilder Action Creators
export const INIT_INGREDIENTS_SUCCESS = "INIT_INGREDIENTS_SUCCESS";
export const INIT_INGREDIENTS_FAILED = "INIT_INGREDIENTS_FAILED";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";

// BurgerBuilder Sagas
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'

// Orders Action Creators
export const PURCHASE_INIT = 'INIT_PURCHASE';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const INIT_ORDERS_START = 'INIT_ORDERS_START';
export const INIT_ORDERS_SUCCESS = 'INIT_ORDERS_SUCCESS';
export const INIT_ORDERS_FAILED = 'INIT_ORDERS_FAILED';

// Orders Sagas
export const INIT_ORDERS = 'INIT_ORDERS';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

// Auth Action Creators
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Auth Sagas
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';